dict_sql -in=d:\_mo\tf_usl\in -out=d:\_mo\tf_usl\out 2>log.txt
copy d:\_mo\tf_usl\out\chip_mo.db d:\_mo\_arc\
copy d:\_mo\tf_usl\out\chip_mo.db d:\_mo\chip\EXE
copy d:\_mo\tf_usl\out\_mo_f031.dbf d:\_mo\_arc\
copy d:\_mo\tf_usl\out\_mo_f031.dbf d:\_mo\chip\EXE
copy d:\_mo\tf_usl\out\_mo_f032.dbf d:\_mo\_arc\
copy d:\_mo\tf_usl\out\_mo_f032.dbf d:\_mo\chip\EXE
copy d:\_mo\tf_usl\out\_mo_f033.dbf d:\_mo\_arc\
copy d:\_mo\tf_usl\out\_mo_f033.dbf d:\_mo\chip\EXE
copy d:\_mo\tf_usl\out\_mo_f034.dbf d:\_mo\_arc\
copy d:\_mo\tf_usl\out\_mo_f034.dbf d:\_mo\chip\EXE
copy d:\_mo\tf_usl\out\_mo_f035.dbf d:\_mo\_arc\
copy d:\_mo\tf_usl\out\_mo_f035.dbf d:\_mo\chip\EXE
copy d:\_mo\tf_usl\out\_mo_f036.dbf d:\_mo\_arc\
copy d:\_mo\tf_usl\out\_mo_f036.dbf d:\_mo\chip\EXE
copy d:\_mo\tf_usl\out\_mo_f037.dbf d:\_mo\_arc\
copy d:\_mo\tf_usl\out\_mo_f037.dbf d:\_mo\chip\EXE
copy d:\_mo\tf_usl\out\_mo_f038.dbf d:\_mo\_arc\
copy d:\_mo\tf_usl\out\_mo_f038.dbf d:\_mo\chip\EXE
